"""Typed response models for Retrieval-S API."""

from taproot_sdk.retrieval.models import (
    AccessGrant,
    AccessGranted,
    AccessList,
    AccessRevoked,
    BatchCancelled,
    BatchCreated,
    BatchErrorSample,
    BatchJobInfo,
    BatchJobList,
    BatchProgress,
    BatchResults,
    BatchStatus,
    ChunkInfo,
    ChunkList,
    ChunksDeleted,
    ChunksUploaded,
    DocumentDeleted,
    DocumentDetail,
    DocumentInfo,
    DocumentList,
    IndexParams,
    IngestionJob,
    JobCancelled,
    JobDetail,
    JobList,
    JobSummary,
    QueryHit,
    QueryResponse,
    StoreCreated,
    StoreDeleted,
    StoreInfo,
    StoreList,
    StoreStatistics,
)

__all__ = [
    # Store models
    "IndexParams",
    "StoreInfo",
    "StoreList",
    "StoreCreated",
    "StoreDeleted",
    "StoreStatistics",
    # Access control
    "AccessGrant",
    "AccessGranted",
    "AccessList",
    "AccessRevoked",
    # Query
    "QueryHit",
    "QueryResponse",
    # Ingestion
    "IngestionJob",
    "JobDetail",
    "JobSummary",
    "JobList",
    "JobCancelled",
    # Batch ingestion
    "BatchProgress",
    "BatchResults",
    "BatchErrorSample",
    "BatchCreated",
    "BatchStatus",
    "BatchJobInfo",
    "BatchJobList",
    "BatchCancelled",
    # Documents
    "DocumentInfo",
    "DocumentDetail",
    "DocumentList",
    "DocumentDeleted",
    # Chunks
    "ChunkInfo",
    "ChunkList",
    "ChunksUploaded",
    "ChunksDeleted",
]
